FROM node:14-alpine3.10

LABEL version=""
LABEL description="Development image for the MERN Library API"

WORKDIR /app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install && npm cache clean --force

COPY . .

#use EXPOSE command to have our port mapped by the docker daemon
EXPOSE 5000

CMD [ "npm", "run", "dev" ]
